apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-secure-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-secure-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-secure-app
    spec:
      containers:
      - name: secure-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
