apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-secure-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-secure-app
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
