apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secure-app-stage
  namespace: argocd
spec:
  destination:
    namespace: stage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/overlays/stage
    repoURL: ##YOUR_REPO_URL##
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
